import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { syncBuiltinESMExports } from 'node:module';
import { once } from 'node:events';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { watchSpecTree } from './spec-watcher.mjs';

test('recursive watcher observes nested creation and atomic replacement only inside .specs', { timeout: 10000 }, async t => {
  const repo = fs.realpathSync(fs.mkdtempSync(join(tmpdir(), 'spec-watch-')));
  const root = join(repo, '.specs'), outside = join(repo, 'source');
  fs.mkdirSync(root); fs.mkdirSync(outside);
  fs.writeFileSync(join(outside, 'private.txt'), 'outside');
  fs.symlinkSync(outside, join(root, 'external'));
  const nativePaths = [], nativeWatch = fs.watch;
  t.mock.method(fs, 'watch', (...args) => { nativePaths.push(resolve(String(args[0]))); return nativeWatch(...args); });
  syncBuiltinESMExports();
  let watcher;
  t.after(async () => {
    await watcher?.close();
    t.mock.restoreAll(); syncBuiltinESMExports();
    fs.rmSync(repo, { recursive: true, force: true });
  });
  let invalidations = 0;
  watcher = watchSpecTree(root, () => invalidations++);
  const events = [];
  watcher.on('all', (event, path) => events.push({ event, path }));
  await once(watcher, 'ready', { signal: AbortSignal.timeout(5000) });
  const changed = (event, path) => new Promise((accept, reject) => {
    const timer = setTimeout(() => { watcher.off(event, listener); reject(new Error(`Missing ${event}: ${path}`)); }, 3000);
    const listener = actual => { if (actual === path) { clearTimeout(timer); watcher.off(event, listener); accept(); } };
    watcher.on(event, listener);
  });
  const nested = join(root, 'feature', 'runtime', 'new', 'receipt.json');
  const added = changed('add', nested);
  fs.mkdirSync(join(root, 'feature', 'runtime', 'new'), { recursive: true });
  fs.writeFileSync(nested, '{}');
  await added;
  const replaced = changed('change', nested);
  fs.writeFileSync(nested + '.tmp', '{"state":"complete"}');
  fs.renameSync(nested + '.tmp', nested);
  await replaced;
  assert.ok(invalidations > 0);
  fs.writeFileSync(join(outside, 'private.txt'), 'changed outside');
  fs.writeFileSync(join(repo, 'README'), 'unrelated root change');
  await new Promise(resolve => setTimeout(resolve, 200));
  assert.ok(nativePaths.length > 0);
  assert.ok(nativePaths.every(path => path === root || path.startsWith(root + '/')), JSON.stringify(nativePaths));
  assert.ok(events.every(({ path }) => !path.includes('/external/') && path.startsWith(root + '/')), JSON.stringify(events));
  await watcher.close();
  assert.equal(watcher.closed, true);
  const afterClose = invalidations;
  fs.writeFileSync(nested, '{}');
  await new Promise(resolve => setTimeout(resolve, 50));
  assert.equal(invalidations, afterClose);
  assert.throws(() => watchSpecTree(repo, () => {}), /canonical .specs/);
  fs.symlinkSync(root, join(repo, 'alias'));
  assert.throws(() => watchSpecTree(join(repo, 'alias'), () => {}), /canonical .specs/);
});
